version: 0.0
os: linux
files:
  - source: /
    destination: /vipul
hooks:
  BeforeInstall:
    - location: /vipul/BeforeInstallHook.sh
      timeout: 300
  AfterInstall:
    - location: /vipul/AfterInstallHook.sh
      timeout: 300
