version: 0.2

phases:
  pre_build:
   commands:
       - echo "creating nodejs folder"
       - mkdir -p ./vipulnodejs/
  build:
    commands:
        - echo "Copying the file"
        - cp index.js ./vipulnodejs/
artifacts:
  files:
    - '**/*'
